name: Continuous Integration

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [macos, ubuntu, windows]

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -B build
        -D TryForC_DEVELOPER_MODE=1
        -D CMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build build --config Debug -j 2

    - name: Install
      run: cmake --install build --config Debug --prefix prefix

    - name: Test
      working-directory: build
      run: ctest --output-on-failure -C Debug -j 2
